function keypoints = keypoints_leg(in1,in2)
%KEYPOINTS_LEG
%    KEYPOINTS = KEYPOINTS_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    25-Sep-2015 17:13:03

l_AC = in2(15,:);
l_DE = in2(16,:);
l_OA = in2(13,:);
l_OB = in2(14,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = l_OA.*t2;
t4 = th1+th2;
t5 = sin(t4);
t6 = l_AC.*t5;
t7 = l_OB.*t2;
t8 = cos(th1);
t9 = cos(t4);
keypoints = reshape([t3,-l_OA.*t8,t7,-l_OB.*t8,t3+t6,-l_AC.*t9-l_OA.*t8,t6+t7,-l_AC.*t9-l_OB.*t8,t6+t7+l_DE.*t2,-l_AC.*t9-l_DE.*t8-l_OB.*t8],[2, 5]);
